#!/bin/sh

# script/bootstrap
# Resolve all dependencies that the application requires to
# run.

set -e

cd "$(dirname "$0")/.."

if [ -f "Brewfile" ]; then
  brew update

  brew bundle check 2>&1 >/dev/null || {
    echo "==> Installing Homebrew dependencies…"
    brew bundle
  }
fi

if type yarn > /dev/null; then
  echo "==> Installing npm dependencies"
  yarn install
fi
